### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by kaitwalla** [klavenjones/open-forum-backend#9]
When I run `npm run db:setup` from the readme on the latest commit on `main`, I get this error:

`missing script: db:setup`

**Comment by klavenjones** [comment]
@kaitwalla Ok I'll look into it right now.

**Comment by kaitwalla** [comment]
I was incorrect, the actual issue is the app assumes it can connect via the system user to the Postgres database to create the role, which is not a standard Postgres setup. Regardless, I still can't install it.
